- name: "Create {{ fish_prompt_file_path }} parent directories, if not exist"
  ansible.builtin.file:
    path: "{{ fish_prompt_file_path | dirname }}"
    state: directory
    owner: "{{ user_name }}"
    mode: '755'
  become: true
  become_user: root

- name: "Config shell prompt in function '{{ fish_prompt_file_path }}'"
  ansible.builtin.template:
    dest: "{{ fish_prompt_file_path }}"
    src: "fish_prompt.j2"
    owner: "{{ user_name }}"
    mode: '644'
    force: yes
  become: true
  become_user: root

