- name: "Install fish shell"
  ansible.builtin.include_tasks: install_fish/main.yml

- name: "Update fish shell completions"
  ansible.builtin.include_tasks: update_completions/main.yml
  when: update_fish_completions

- name: "Configure main fish config file"
  ansible.builtin.include_tasks: config_main/main.yml

- name: "Configure fish shell prompt"
  ansible.builtin.include_tasks: config_prompt/main.yml

