- name: "Install fish shell"
  ansible.builtin.include_tasks: install_fish.yml

- name: "Update fish shell completions"
  ansible.builtin.include_tasks: update_completions.yml

- name: "Create subdirectory for fish function files"
  ansible.builtin.include_tasks: create_functions_dir.yml

- name: "Configure fish shell prompt"
  ansible.builtin.include_tasks: config_prompt.yml

