- name: "Create {{ fish_functions_dir }} parent directories, if not exist"
  ansible.builtin.file:
    path: "{{ fish_functions_dir }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '755'
  become: true
  become_user: root

