# if true, update fish shell completions each time the role is run
fish_update_completions: true

# an optional list of functions to define (to run at CLI, like aliases)
# --> Use $argv for the full list of args
# --> Use $argv[x] for a specific positional arg (first arg is $argv[1])
# --> Use (count $argv) for the number of args
fish_command_functions: []
# fish_command_functions:
#   - { name: 'newsboat', body: 'newsboat --quiet $argv', descrip: 'silence newsboat startup warnings' }

# use this command to show the git branch in the shell prompt
# note: the default 'true' command has no output, so nothing is shown
fish_prompt_show_git_branch_cmd: 'true'

